### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [156]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [157]:
lst=[23,34,4523,12]
ar=np.array(lst)
print(ar)

[  23   34 4523   12]


In [158]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [159]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [160]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [161]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [162]:
# with reshape
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [163]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [164]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [165]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [166]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [167]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


### Array Attributes

In [168]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [169]:
# ndim
a3.ndim

3

In [170]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [171]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [172]:
# itemsize   It returns the number of bytes used to represent a single element of the array. 
a3.itemsize

4

In [173]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [174]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations

In [175]:
a1 = np.arange(12).reshape(3,4).astype(np.int64)
a2 = np.arange(12,24).reshape(3,4).astype(np.int64)
print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]], dtype=int64)

In [176]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int64)

In [177]:
#realtional 
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [178]:
#vector opration
#arithmatic 

print(a1)
print(a2)
(a1 ** a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]], dtype=int64)

### Array Functions


In [191]:
a1 = np.random.random((3,3))
a1 = np.round(a1*10)
a1

array([[ 7.,  2.,  4.],
       [ 2.,  4., 10.],
       [ 1.,  6.,  8.]])

In [193]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 14.,  48., 320.])

In [194]:
# mean/median/std/var
np.var(a1,axis=1)

array([ 4.22222222, 11.55555556,  8.66666667])

In [195]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.6569866 ,  0.90929743, -0.7568025 ],
       [ 0.90929743, -0.7568025 , -0.54402111],
       [ 0.84147098, -0.2794155 ,  0.98935825]])

In [196]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [197]:
# log and exponents
np.exp(a1)

array([[1.09663316e+03, 7.38905610e+00, 5.45981500e+01],
       [7.38905610e+00, 5.45981500e+01, 2.20264658e+04],
       [2.71828183e+00, 4.03428793e+02, 2.98095799e+03]])

In [198]:
np.log(a1)

array([[1.94591015, 0.69314718, 1.38629436],
       [0.69314718, 1.38629436, 2.30258509],
       [0.        , 1.79175947, 2.07944154]])

In [199]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[ 2., 51., 47.],
       [97., 77., 59.]])

### Indexing and Slicing

In [200]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [201]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
a2[1,0]

4

In [206]:
#arrayName[row,column]

In [207]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [208]:
a3[1,0,1]

5

In [216]:
#special work
d=np.array(a3.shape)
print(d)

[2 2 2]


In [217]:
a3[1,1,0]

6

In [218]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
a1[2:5:2]

array([2, 4])

In [224]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [226]:
a2[1,::3]

array([4, 7])

In [227]:
a2[0,:]

array([0, 1, 2, 3])

In [230]:
a2[:,2]

array([ 2,  6, 10])

In [233]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [234]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [235]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [236]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [237]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [238]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [239]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [240]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [241]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [242]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [245]:
for i in np.nditer(a3):
  print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

### Reshaping

In [246]:
#reshape

# Example 1: Reshaping a 1D array to a 2D array
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = np.reshape(arr1d, (2, 3))

print("Original 1D array:")
print(arr1d)

print("\nReshaped 2D array:")
print(arr2d)

Original 1D array:
[1 2 3 4 5 6]

Reshaped 2D array:
[[1 2 3]
 [4 5 6]]


In [247]:
# Example 2: Reshaping a 2D array to a 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.reshape(arr2d, (6,))

print("Original 2D array:")
print(arr2d)

print("\nReshaped 1D array:")
print(arr1d)

Original 2D array:
[[1 2 3]
 [4 5 6]]

Reshaped 1D array:
[1 2 3 4 5 6]


In [251]:
# Transpose
np.transpose(a2)


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [252]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [254]:
# ravel making into 1D list
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [256]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [257]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [258]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [259]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [263]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [271]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]