### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([66, 16, 85, 64,  1, 42, 80, 36, 45, 42, 63, 90, 77, 99, 13])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[74, 71, 90, 40],
       [34, 98, 25, 39],
       [77, 88, 91, 85],
       [66, 63,  3, 75],
       [76, 14, 53, 63],
       [79, 13, 37, 84]])

In [18]:
np.sort(a)[::-1]

array([99, 90, 85, 80, 77, 66, 64, 63, 45, 42, 42, 36, 16, 13,  1])

In [19]:
np.sort(b,axis=0)

array([[34, 13,  3, 39],
       [66, 14, 25, 40],
       [74, 63, 37, 63],
       [76, 71, 53, 75],
       [77, 88, 90, 84],
       [79, 98, 91, 85]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [20]:
# code
np.append(a,200)

array([ 66,  16,  85,  64,   1,  42,  80,  36,  45,  42,  63,  90,  77,
        99,  13, 200])

In [21]:
b

array([[74, 71, 90, 40],
       [34, 98, 25, 39],
       [77, 88, 91, 85],
       [66, 63,  3, 75],
       [76, 14, 53, 63],
       [79, 13, 37, 84]])

In [32]:
b.shape[0]
np.random.random((6,2))

array([[0.41560047, 0.3095924 ],
       [0.60225563, 0.9154612 ],
       [0.60923269, 0.79509734],
       [0.40930528, 0.67216008],
       [0.85871042, 0.50549301],
       [0.0421258 , 0.94664741]])

In [24]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[74.        , 71.        , 90.        , 40.        ,  0.57782839],
       [34.        , 98.        , 25.        , 39.        ,  0.80746631],
       [77.        , 88.        , 91.        , 85.        ,  0.98578782],
       [66.        , 63.        ,  3.        , 75.        ,  0.23214447],
       [76.        , 14.        , 53.        , 63.        ,  0.39739675],
       [79.        , 13.        , 37.        , 84.        ,  0.61560845]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [33]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [35]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [54]:
# code
e = np.array(np.random.randint(1,19,15))
np.unique(e)

array([ 2,  5,  6,  8,  9, 10, 11, 12, 13, 15, 17, 18])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [55]:
# code
a.shape

(10,)

In [56]:
np.expand_dims(a,axis=0)

array([[17, 12, 16, 18, 18, 12,  1, 17,  8, 15]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [57]:
a=e

In [58]:
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [59]:
# find all indices with value greater than 50
np.where(a>10)

(array([ 2,  5,  7,  8,  9, 11, 13], dtype=int64),)

In [60]:
# replace all values > 50 with 0
np.where(a>10,0,a)

array([ 5,  8,  0,  2, 10,  0, 10,  0,  0,  0,  9,  0,  5,  0,  6])

In [61]:
np.where(a%2 == 0,0,a)

array([ 5,  0,  0,  0,  0, 11,  0,  0, 15, 17,  9, 13,  5, 15,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [62]:
# code
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [63]:
np.argmax(a)

2

In [64]:
b

array([[74, 71, 90, 40],
       [34, 98, 25, 39],
       [77, 88, 91, 85],
       [66, 63,  3, 75],
       [76, 14, 53, 63],
       [79, 13, 37, 84]])

In [65]:
np.argmax(b,axis=0)

array([5, 1, 2, 2], dtype=int64)

In [66]:
np.argmax(b,axis=1)

array([2, 1, 2, 3, 0, 3], dtype=int64)

In [67]:
# np.argmin
np.argmin(a)

3

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [68]:
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [69]:
np.cumsum(a)

array([  5,  13,  31,  33,  43,  54,  64,  76,  91, 108, 117, 130, 135,
       150, 156])

In [99]:
b=np.random.randint(1,50,24).reshape(6,4).astype(np.int64)
b

array([[40, 16, 44, 27],
       [38,  6, 10,  5],
       [14, 12, 49, 47],
       [41, 42,  8, 26],
       [17, 33, 26, 15],
       [ 9, 22, 27, 46]], dtype=int64)

In [100]:
np.cumsum(b,axis=0)

array([[ 40,  16,  44,  27],
       [ 78,  22,  54,  32],
       [ 92,  34, 103,  79],
       [133,  76, 111, 105],
       [150, 109, 137, 120],
       [159, 131, 164, 166]], dtype=int64)

In [101]:
# np.cumprod
np.cumprod(b)

array([                  40,                  640,                28160,
                     760320,             28892160,            173352960,
                 1733529600,           8667648000,         121347072000,
              1456164864000,       71352078336000,     3353547681792000,
         137495454953472000,  5774809108045824000, -9141759356762062848,
        2121929682410536960,  -820683546439974912, -8635812958809620480,
       -3170208044535513088,  7787111553095958528, -3702972316974579712,
       -7678414678602547200, -4403011511463706624,   375655283474563072],
      dtype=int64)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [102]:
np.percentile(a,50)

10.0

In [104]:
np.median(a)

10.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [105]:
# code
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [106]:
np.histogram(a,bins=[0,50,100])

(array([15,  0], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [107]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [108]:
# code
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [109]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([10, 10])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [110]:
# code
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [111]:
np.flip(a)

array([ 6, 15,  5, 13,  9, 17, 15, 12, 10, 11, 10,  2, 18,  8,  5])

In [112]:
b

array([[40, 16, 44, 27],
       [38,  6, 10,  5],
       [14, 12, 49, 47],
       [41, 42,  8, 26],
       [17, 33, 26, 15],
       [ 9, 22, 27, 46]], dtype=int64)

In [114]:
np.flip(b)

array([[46, 27, 22,  9],
       [15, 26, 33, 17],
       [26,  8, 42, 41],
       [47, 49, 12, 14],
       [ 5, 10,  6, 38],
       [27, 44, 16, 40]], dtype=int64)

In [115]:
np.flip(b,axis=1)

array([[27, 44, 16, 40],
       [ 5, 10,  6, 38],
       [47, 49, 12, 14],
       [26,  8, 42, 41],
       [15, 26, 33, 17],
       [46, 27, 22,  9]], dtype=int64)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [116]:
# code
a

array([ 5,  8, 18,  2, 10, 11, 10, 12, 15, 17,  9, 13,  5, 15,  6])

In [117]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [118]:
# code
a

array([110, 530,  18,   2,  10,  11,  10,  12,  15,  17,   9,  13,   5,
        15,   6])

In [119]:
np.delete(a,[0,2,4])

array([530,   2,  11,  10,  12,  15,  17,   9,  13,   5,  15,   6])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [120]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [121]:
np.intersect1d(m,n)

array([3, 4, 5])

In [122]:
np.setdiff1d(n,m)

array([6, 7])

In [123]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [124]:
# code
a

array([110, 530,  18,   2,  10,  11,  10,  12,  15,  17,   9,  13,   5,
        15,   6])

In [125]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [133]:
# 17. np.swapaxes

# Create a 2x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Swap axes 0 and 1
arr_swapped = np.swapaxes(arr, 0, 1)

print("Original array:")
print(arr)

print("\nArray after swapping axes 0 and 1:")
print(arr_swapped)


Original array:
[[1 2 3]
 [4 5 6]]

Array after swapping axes 0 and 1:
[[1 4]
 [2 5]
 [3 6]]


In [134]:
# 18. np.uniform

# Generate a random number from a uniform distribution
random_number = np.random.uniform(low=0.0, high=1.0)

print("Random number from a uniform distribution:", random_number)

Random number from a uniform distribution: 0.5412736746442551


In [135]:
# Generate a 1D array of 5 random numbers from a uniform distribution
random_numbers = np.random.uniform(low=0.0, high=1.0, size=5)

print("Random numbers from a uniform distribution:")
print(random_numbers)

Random numbers from a uniform distribution:
[0.42654415 0.4620304  0.18687782 0.14683574 0.70423528]


In [136]:
# 19. np.count_nonzero



# Create an array with some zeros and non-zeros
arr = b

# Count the number of non-zero elements in the entire array
count_all = np.count_nonzero(arr)

# Count the number of non-zero elements along each axis
count_axis_0 = np.count_nonzero(arr, axis=0)
count_axis_1 = np.count_nonzero(arr, axis=1)

print("Original array:")
print(arr)

print("\nNumber of non-zero elements in the entire array:", count_all)

print("\nNumber of non-zero elements along axis 0:", count_axis_0)
print("Number of non-zero elements along axis 1:", count_axis_1)


Original array:
[[40 16 44 27]
 [38  6 10  5]
 [14 12 49 47]
 [41 42  8 26]
 [17 33 26 15]
 [ 9 22 27 46]]

Number of non-zero elements in the entire array: 24

Number of non-zero elements along axis 0: [6 6 6 6]
Number of non-zero elements along axis 1: [4 4 4 4 4 4]


In [137]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

# Create a simple array
arr = np.array([[1, 2],
                [3, 4]])

# Tile the array three times along each axis
tiled_arr = np.tile(arr, (3, 2))

print("Original array:")
print(arr)

print("\nTiled array:")
print(tiled_arr)

Original array:
[[1 2]
 [3 4]]

Tiled array:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [138]:
# Tile the scalar value 5, three times
tiled_scalar = np.tile(5, 3)

print("Tiled scalar:")
print(tiled_scalar)

Tiled scalar:
[5 5 5]


In [139]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

# Create a simple array
arr = np.array([1, 2, 3])

# Repeat each element three times
repeated_arr = np.repeat(arr, 3)

print("Original array:")
print(arr)

print("\nRepeated array:")
print(repeated_arr)

Original array:
[1 2 3]

Repeated array:
[1 1 1 2 2 2 3 3 3]


In [140]:
# Create a 2D array
arr = np.array([[1, 2],
                [3, 4]])

# Repeat along axis 0 (rows)
repeated_arr_axis_0 = np.repeat(arr, 3, axis=0)

# Repeat along axis 1 (columns)
repeated_arr_axis_1 = np.repeat(arr, 3, axis=1)

print("Original array:")
print(arr)

print("\nRepeated array along axis 0:")
print(repeated_arr_axis_0)

print("\nRepeated array along axis 1:")
print(repeated_arr_axis_1)

Original array:
[[1 2]
 [3 4]]

Repeated array along axis 0:
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]

Repeated array along axis 1:
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]


In [141]:

# 25. np.allclose and equals


arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.000001, 2.000002, 3.000003])

result = np.allclose(arr1, arr2, atol=1e-5, rtol=1e-5)



# ** <span style="color: red;"> IT WAS A NICE JOURNEY WITH NUMPY </span> **